const GET_NAMES = "GET_NAMES";
const ADD_NAME = "ADD_NAME";
const DELETE_NAME = "DELETE_NAME";
const LOAD_ING = "LOAD_ING";
const GET_LENGTH = "GET_LENGTH";

export { GET_NAMES, ADD_NAME, DELETE_NAME, LOAD_ING, GET_LENGTH };
